Here is the equivalent Github Action configuration file:

```yaml
name: Python application

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 2.7
      uses: actions/setup-python@v2
      with:
        python-version: 2.7
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r test_requirements.txt

    - name: Run tests
      run: make test
```

This Github Action configuration file does the following:

1. Defines a workflow that runs on every push and pull request.
2. Sets up the environment to run on the latest version of Ubuntu.
3. Checks out your repository using `actions/checkout@v2`.
4. Sets up Python 2.7, 3.6, 3.7, 3.8, and 3.9 using `actions/setup-python@v2`.
5. Installs the dependencies listed in `requirements.txt` and `test_requirements.txt`.
6. Runs the `make test` command to run the tests.
